name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: newdb
        ports:
          - 3306:3306

    env:
      DB_URL: jdbc:mysql://127.0.0.1:3306/newdb
      DB_USERNAME: root
      DB_PASSWORD: root
      DOCKER_IMAGE_BACKEND: ${{ secrets.DOCKER_USERNAME }}/course-backend
      DOCKER_IMAGE_FRONTEND: ${{ secrets.DOCKER_USERNAME }}/course-frontend

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    # 🔐 SAST
    - name: Gitleaks Scan
      uses: gitleaks/gitleaks-action@v2
      continue-on-error: true

    - name: Trivy FS Scan
      uses: aquasecurity/trivy-action@v0.24.0
      with:
        scan-type: fs
        severity: CRITICAL,HIGH
      continue-on-error: true

    # ☕ Backend
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Backend
      run: |
        cd backend
        chmod +x mvnw
        ./mvnw clean package -DskipTests

    - name: Run Backend Tests
      run: |
        cd backend
        ./mvnw test

    # 🌐 Frontend
    - name: Set up Node
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Build Frontend
      run: |
        cd frontend
        npm install
        npm run build

    # 🐳 Docker
    - name: Build Docker Images
      run: docker compose build

    # 🔐 Image Scan
    - name: Scan Backend Image
      uses: aquasecurity/trivy-action@v0.24.0
      with:
        image-ref: ${{ env.DOCKER_IMAGE_BACKEND }}
        severity: CRITICAL,HIGH
      continue-on-error: true

    - name: Scan Frontend Image
      uses: aquasecurity/trivy-action@v0.24.0
      with:
        image-ref: ${{ env.DOCKER_IMAGE_FRONTEND }}
        severity: CRITICAL,HIGH
      continue-on-error: true

    # 🔐 Push
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push Backend Image
      run: |
        docker build -t $DOCKER_IMAGE_BACKEND ./backend
        docker push $DOCKER_IMAGE_BACKEND

    - name: Push Frontend Image
      run: |
        docker build -t $DOCKER_IMAGE_FRONTEND ./frontend
        docker push $DOCKER_IMAGE_FRONTEND

    # 🚀 Run App
    - name: Start App
      run: docker compose up -d

    - name: Wait for App
      run: sleep 20

    # 🛡️ DAST
    - name: OWASP ZAP Scan
      uses: zaproxy/action-baseline@v0.12.0
      with:
        target: 'http://localhost:9090'
      continue-on-error: true

    # 🧹 Cleanup
    - name: Stop App
      run: docker compose down
